import Head from 'next/head'
import Logo from '@/comps/Logo'
import MyButton from '@/comps/Button'
import styled from'styled-components'
import Footer from '@/comps/Footer' 

const Wrapper=styled.div`
width:100%;
height:100vh;
display:flex;
flex-direction:column;
justify-content: center;
align-items:center;
`

const Container=styled.div`
width:50rem;
height:65rem;
display:flex;
flex-direction:column;
justify-content: flex-start;
align-items:center;
border:2px solid lightgrey;
border-radius:2rem;

`

const ButtonCon=styled.div`
width:100%;
height:10rem;
display:flex;
flex-direction:column;
justify-content:space-around;
align-items:center;
`
const TextCon=styled.p`
width:40%;
justify-content:center;
align-items:center;
font-size:1rem;
text-align:center;
margin:.5rem
`

export default function Home() {
  return (
    <div>
      <Head>
        <title>LEBRARY</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Wrapper>
      
      <Container>
        <Logo/>
        <ButtonCon>
        <MyButton routeTo ="/books/" />
        <MyButton text="setting" routeTo ="/setting"/>
        </ButtonCon>
      </Container>
      <Footer/>
      </Wrapper>

    </div>
  )
}
